language: perl
perl:
    - "5.10"
    - "5.12"

branches:
  only:
    - develop

before_install:
    - "sudo apt-get update"
    - "sudo apt-get install libdb-dev"
    - "cpanm DB_File DBI Data::Stag"
    - "sudo apt-get install libxml2-dev"

notifications:
    email: false
    
env: 
    PERL_CPANM_OPT="--notest"
