language: perl
perl:
    - "5.10"

branches:
  only:
    - feature/travis-ci

before_install:
    - "sudo apt-get update"
    - "sudo apt-get install libdb-dev"
    - "cpanm DB_File"
    - "sudo apt-get install libxml2-dev"

notifications:
    email: false
    
env: 
    PERL_CPANM_OPT="-v --notest"
