language: perl
perl:
    - "5.12"
    - "5.10"

branches:
  only:
    - feature/redesign-arch

before_install:
    - "cpanm -n DBI DB_File Data::Stag"

notifications:
    email: false
    
env: 
    PERL_CPANM_OPT="-v --notest"
